https-portal:
  image: steveltn/https-portal:1
  ports:
    - "80:80"
    - "443:443"
  links:
    - nginx
  restart: always
  environment:
    DOMAINS: "kotaroooo0.com -> http://nginx:8000"
    STAGE: "production"
    # FORCE_RENEW: "true"

nginx:
  build: "."
  ports:
    - "8000:8000"
