version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: portfolio-https-portal
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      STAGE: "production"
      DOMAINS: >-
        www.kotaroooo0.com
    volumes:
      - ./src:/var/www/vhosts/www.kotaroooo0.com
      - /data/ssl_certs:/var/lib/https-portal
